// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzH9-D58FwDmA3696EX_ajoOrHQRZkxiE',
    appId: '1:519271400835:web:b64fab60b20de393b8a2b6',
    messagingSenderId: '519271400835',
    projectId: 'eshop-a44ca',
    authDomain: 'eshop-a44ca.firebaseapp.com',
    storageBucket: 'eshop-a44ca.appspot.com',
    measurementId: 'G-1VT785RECC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKbqthQFzzFIXg0-L_nZtQ81Hg5lRStuY',
    appId: '1:519271400835:android:a128a2f9d2cfa264b8a2b6',
    messagingSenderId: '519271400835',
    projectId: 'eshop-a44ca',
    storageBucket: 'eshop-a44ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgNRb_e55jgPeZdAGwqtjkfknuMzq3zYw',
    appId: '1:519271400835:ios:b328ff822cea5d0bb8a2b6',
    messagingSenderId: '519271400835',
    projectId: 'eshop-a44ca',
    storageBucket: 'eshop-a44ca.appspot.com',
    iosClientId: '519271400835-83geq4k2qulmub7ngsalgtfqd43i4ik4.apps.googleusercontent.com',
    iosBundleId: 'com.example.eshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgNRb_e55jgPeZdAGwqtjkfknuMzq3zYw',
    appId: '1:519271400835:ios:b328ff822cea5d0bb8a2b6',
    messagingSenderId: '519271400835',
    projectId: 'eshop-a44ca',
    storageBucket: 'eshop-a44ca.appspot.com',
    iosClientId: '519271400835-83geq4k2qulmub7ngsalgtfqd43i4ik4.apps.googleusercontent.com',
    iosBundleId: 'com.example.eshop',
  );
}
